// This file was generated by lezer-generator. You probably shouldn't edit it.
const {LRParser} = require("@lezer/lr")
const {Identifier} = require("./tokens.js")
exports.parser = LRParser.deserialize({
  version: 14,
  states: "nQYQROOOOQQ'#Cj'#CjOOQQ'#Cf'#CfQYQROOOOQQ-E6d-E6d",
  stateData: "q~O]OSVOS~OPPOQPORPOSPOTPOUPOXPO~O",
  goto: "j_PPPPPPPPPP`PPPfQRORSRTQOR",
  nodeNames: "⚠ varOther varReg varWire scopeOther scopeModule hierChange LineComment Program TimeStamp",
  maxTerm: 14,
  skippedNodes: [0,7],
  repeatNodeCount: 1,
  tokenData: "$a~RUXYeYZe]^epqe!P!Qv!b!c!e~jS]~XYeYZe]^epqe~yP!P!Q|~!RSV~OY|Z;'S|;'S;=`!_<%lO|~!bP;=`<%l|~!hP!Q![!k~!nV!Q![!k#Y#Z#T#a#b#T#b#c#T#d#e#T#g#h#j#i#j#T~#WU#Y#Z#T#a#b#T#b#c#T#d#e#T#g#h#j#i#j#T~#oPX~!O!P#r~#uR!Q![$O!c!}$O#T#o$O~$TSX~!O!P#r!Q![$O!c!}$O#T#o$O",
  tokenizers: [0, Identifier],
  topRules: {"Program":[0,8]},
  tokenPrec: 0
})
