// This file was generated by lezer-generator. You probably shouldn't edit it.
module.exports = {
  varOther: 1,
  varReg: 2,
  varWire: 3,
  scopeOther: 4,
  scopeModule: 5,
  hierChange: 6,
  LineComment: 7,
  Program: 8,
  TimeStamp: 9
}